### ISSUE TITLE
On Gnome, I would like to insert emoji like on MacOS

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/my-linux-desktop-journey#2]
On Gnome, I would like to insert emoji like on MacOS.

Solutions to test:

- [ ] https://github.com/maoschanz/emoji-selector-for-gnome/
- [ ] https://github.com/tom-james-watson/Emote

**Comment by stephane-klein** [comment]
Resource:

- [`maoschanz/emoji-selector-for-gnome`](https://github.com/maoschanz/emoji-selector-for-gnome/) [Plans to support GNOME 40? #151](https://github.com/maoschanz/emoji-selector-for-gnome/issues/151)

**Comment by stephane-klein** [comment]
I'm going to test this pull request: https://github.com/maoschanz/emoji-selector-for-gnome/pull/149

**Comment by stephane-klein** [comment]
> I'm going to test this pull request: [maoschanz/emoji-selector-for-gnome#149](https://github.com/maoschanz/emoji-selector-for-gnome/pull/149)

Installed with success on:

```
$ gnome-shell --version
GNOME Shell 40.5
```

**Comment by balazsorban44** [comment]
Awesome, did you just follow the manual installation from the readme on the PR branch? I'll have to give it a try as well!

**Comment by stephane-klein** [comment]
Fixed: `https://github.com/maoschanz/emoji-selector-for-gnome/issues/151#issuecomment-1201361921`
